### ISSUE TITLE
Add polyfill for forEach to ensure IE compatibility

### ISSUE THREAD

**Issue by axellabs** [HubSpot/cms-theme-boilerplate#89]
The boilerplate menu needs to be refactored to remove `forEach` in order to ensure IE11 compatibility.

**Comment by corymartin** [comment]
Array's `forEach`? If so that should work back to IE9
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

The project's  eslintrc file does not specify `ecmaVersion`.  Which, from my reading of the docs, means the project is already assumed to be ES5 as the default.
https://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by jfudman** [comment]
Could we just provide a [forEach polyfill](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Polyfill)?

If not, then the [styleguide](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md#javascript-code-formatting) will also need to be updated in Javascript formatting.

**Comment by jasonnrosa** [comment]
@corymartin I believe this is in reference to NodeList.prototype (https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) - I think the polyfill would work to @jfudman point so we can work to get the style guide and code updated with that.
